title: Sameal Con-Roma
description: Cybersecurity Portfolio
show_downloads: false
google_analytics: 
theme: jekyll-theme-hacker
contact_info: 
  linkedin: "[LinkedIn](https://www.linkedin.com/in/sameal/)"
  email: "sconroma@protonmail.com"
